"""Orders service: creates and lists orders, backed by PostgreSQL.

Orders are validated against the users and products services, and the product
name and unit price are snapshotted so past orders never change.
"""
import logging
import os
import threading
from collections import defaultdict
from contextlib import contextmanager
from decimal import Decimal

import psycopg2
import requests
from flask import Flask, abort, jsonify, request, url_for
from psycopg2 import pool
from psycopg2.extras import RealDictCursor
from werkzeug.exceptions import HTTPException

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("orders-api")

app = Flask(__name__)

USERS_API = os.environ.get("USERS_API", "http://localhost:5001").rstrip("/")
PRODUCTS_API = os.environ.get("PRODUCTS_API", "http://localhost:5002").rstrip("/")
HTTP_TIMEOUT = float(os.environ.get("HTTP_TIMEOUT", "5"))

MAX_ITEMS = 50
MAX_QUANTITY = 100

# --------------------------------------------------------------------------
# Database configuration & connection pool
# --------------------------------------------------------------------------
DB_CONFIG = {
    "host": os.environ.get("DB_HOST", "localhost"),
    "port": int(os.environ.get("DB_PORT", "5432")),
    "dbname": os.environ.get("DB_NAME", "ecommerce"),
    "user": os.environ.get("DB_USER", "postgres"),
    "password": os.environ.get("DB_PASS", ""),
    "connect_timeout": int(os.environ.get("DB_CONNECT_TIMEOUT", "5")),
}
DB_POOL_MAX = int(os.environ.get("DB_POOL_MAX", "10"))

SCHEMA_LOCK_ID = 7003  # advisory lock so concurrent workers don't race on DDL
SCHEMA = """
CREATE TABLE IF NOT EXISTS orders (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    user_id    INTEGER       NOT NULL,
    total      NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    status     TEXT          NOT NULL DEFAULT 'created',
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS orders_user_id_idx ON orders (user_id);

CREATE TABLE IF NOT EXISTS order_items (
    id           SERIAL PRIMARY KEY,
    order_id     INTEGER       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   INTEGER       NOT NULL,
    product_name TEXT          NOT NULL,
    unit_price   NUMERIC(10,2) NOT NULL,
    quantity     INTEGER       NOT NULL CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items (order_id);
"""

_pool = None
_pool_lock = threading.Lock()


def initialise_schema(db_pool):
    """Create tables on first start."""
    conn = db_pool.getconn()
    try:
        with conn, conn.cursor() as cur:
            cur.execute("SELECT pg_advisory_xact_lock(%s)", (SCHEMA_LOCK_ID,))
            cur.execute(SCHEMA)
    finally:
        db_pool.putconn(conn)


def get_pool():
    """Lazily create the pool so the service can start before the DB is ready."""
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                new_pool = pool.ThreadedConnectionPool(1, DB_POOL_MAX, **DB_CONFIG)
                try:
                    initialise_schema(new_pool)
                except Exception:
                    new_pool.closeall()
                    raise
                _pool = new_pool
                logger.info("Connected to database %s@%s", DB_CONFIG["dbname"], DB_CONFIG["host"])
    return _pool


@contextmanager
def db_cursor():
    """Yield a dict cursor; commit on success, roll back on error."""
    db_pool = get_pool()
    conn = db_pool.getconn()
    try:
        with conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
            yield cur
    finally:
        db_pool.putconn(conn)


# --------------------------------------------------------------------------
# Validation, upstream calls & error handling
# --------------------------------------------------------------------------
class ValidationError(ValueError):
    """Raised when a request payload is invalid."""


class UpstreamError(Exception):
    """Raised when a dependent service cannot be reached or misbehaves."""


def is_int(value):
    return isinstance(value, int) and not isinstance(value, bool)


def read_json_object():
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        raise ValidationError("Request body must be a JSON object")
    return data


def parse_order(data):
    """Return (user_id, {product_id: quantity}) from the request payload."""
    user_id = data.get("user_id")
    if not is_int(user_id) or user_id < 1:
        raise ValidationError("'user_id' must be a positive integer")

    items = data.get("items")
    if not isinstance(items, list) or not 1 <= len(items) <= MAX_ITEMS:
        raise ValidationError(f"'items' must be a list of 1-{MAX_ITEMS} entries")

    quantities = {}
    for item in items:
        if not isinstance(item, dict):
            raise ValidationError("Each item must be an object")
        product_id = item.get("product_id")
        quantity = item.get("quantity", 1)
        if not is_int(product_id) or product_id < 1:
            raise ValidationError("Each item needs a positive integer 'product_id'")
        if not is_int(quantity) or not 1 <= quantity <= MAX_QUANTITY:
            raise ValidationError(f"'quantity' must be an integer between 1 and {MAX_QUANTITY}")
        quantities[product_id] = quantities.get(product_id, 0) + quantity
        if quantities[product_id] > MAX_QUANTITY:
            raise ValidationError(f"Cannot order more than {MAX_QUANTITY} of one product")
    return user_id, quantities


def fetch_json(url, label):
    """GET a JSON resource from a sibling service; None if it returns 404."""
    try:
        resp = requests.get(url, timeout=HTTP_TIMEOUT)
    except requests.RequestException as exc:
        logger.error("%s service unreachable: %s", label, exc)
        raise UpstreamError(f"{label} service is unavailable") from exc
    if resp.status_code == 404:
        return None
    if not resp.ok:
        logger.error("%s service returned %s for %s", label, resp.status_code, url)
        raise UpstreamError(f"{label} service returned an error")
    try:
        return resp.json()
    except ValueError as exc:
        raise UpstreamError(f"{label} service returned an invalid response") from exc


@app.errorhandler(ValidationError)
def handle_validation_error(err):
    return jsonify(error=str(err)), 400


@app.errorhandler(UpstreamError)
def handle_upstream_error(err):
    return jsonify(error=str(err)), 502


@app.errorhandler(HTTPException)
def handle_http_error(err):
    return jsonify(error=err.description or err.name), err.code


@app.errorhandler(psycopg2.OperationalError)
@app.errorhandler(pool.PoolError)
def handle_db_unavailable(err):
    logger.error("Database unavailable: %s", err)
    return jsonify(error="Database unavailable"), 503


@app.errorhandler(Exception)
def handle_unexpected(err):
    logger.exception("Unhandled error")
    return jsonify(error="Internal server error"), 500


# --------------------------------------------------------------------------
# Data access
# --------------------------------------------------------------------------
def fetch_orders(cur, where="TRUE", params=(), limit=100):
    """Return orders (newest first) with their line items attached.

    `where` must be a trusted SQL fragment; values go through `params`.
    """
    cur.execute(
        "SELECT o.id, o.user_id, o.total, o.status, o.created_at "
        f"FROM orders o WHERE {where} ORDER BY o.id DESC LIMIT %s",
        (*params, limit),
    )
    orders = cur.fetchall()
    if not orders:
        return []

    cur.execute(
        "SELECT order_id, product_id, product_name, unit_price, quantity "
        "FROM order_items WHERE order_id = ANY(%s) ORDER BY id",
        ([order["id"] for order in orders],),
    )
    items_by_order = defaultdict(list)
    for row in cur.fetchall():
        items_by_order[row["order_id"]].append(
            {
                "product_id": row["product_id"],
                "product_name": row["product_name"],
                "unit_price": float(row["unit_price"]),
                "quantity": row["quantity"],
            }
        )

    return [
        {
            "id": order["id"],
            "user_id": order["user_id"],
            "total": float(order["total"]),
            "status": order["status"],
            "created_at": order["created_at"].isoformat(),
            "items": items_by_order[order["id"]],
        }
        for order in orders
    ]


# --------------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------------
@app.get("/health")
def health():
    with db_cursor() as cur:
        cur.execute("SELECT 1")
    return jsonify(status="ok")


@app.get("/orders")
def list_orders():
    user_id = request.args.get("user_id", type=int)
    with db_cursor() as cur:
        if user_id is None:
            orders = fetch_orders(cur)
        else:
            orders = fetch_orders(cur, "o.user_id = %s", (user_id,))
    return jsonify(orders)


@app.get("/orders/<int:order_id>")
def get_order(order_id):
    with db_cursor() as cur:
        orders = fetch_orders(cur, "o.id = %s", (order_id,))
    if not orders:
        abort(404, description="Order not found")
    return jsonify(orders[0])


@app.post("/orders")
def create_order():
    user_id, quantities = parse_order(read_json_object())

    if fetch_json(f"{USERS_API}/users/{user_id}", "Users") is None:
        abort(422, description=f"User {user_id} does not exist")

    ids_str = ",".join(str(pid) for pid in quantities.keys())
    products = fetch_json(f"{PRODUCTS_API}/products?ids={ids_str}", "Products") or []
    product_map = {p["id"]: p for p in products}

    lines = []
    total = Decimal("0.00")
    for product_id, quantity in sorted(quantities.items()):
        product = product_map.get(product_id)
        if product is None:
            abort(422, description=f"Product {product_id} does not exist")
        unit_price = Decimal(str(product["price"])).quantize(Decimal("0.01"))
        total += unit_price * quantity
        lines.append((product_id, product["name"], unit_price, quantity))

    with db_cursor() as cur:
        cur.execute(
            "INSERT INTO orders (user_id, total) VALUES (%s, %s) RETURNING id",
            (user_id, total),
        )
        order_id = cur.fetchone()["id"]
        cur.executemany(
            "INSERT INTO order_items (order_id, product_id, product_name, unit_price, quantity) "
            "VALUES (%s, %s, %s, %s, %s)",
            [(order_id, *line) for line in lines],
        )
        order = fetch_orders(cur, "o.id = %s", (order_id,))[0]

    body = {"message": "Order created", "order_id": order_id, "order": order}
    return jsonify(body), 201, {"Location": url_for("get_order", order_id=order_id)}


if __name__ == "__main__":
    app.run(
        host=os.environ.get("HOST", "0.0.0.0"),
        port=int(os.environ.get("PORT", "5003")),
        debug=os.environ.get("FLASK_DEBUG") == "1",
    )
