"""Products service: product catalogue backed by PostgreSQL."""
import logging
import os
import threading
from contextlib import contextmanager
from decimal import Decimal, InvalidOperation

import psycopg2
from flask import Flask, abort, jsonify, request, url_for
from psycopg2 import pool
from psycopg2.extras import RealDictCursor
from werkzeug.exceptions import HTTPException

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("products-api")

app = Flask(__name__)

# --------------------------------------------------------------------------
# Database configuration & connection pool
# --------------------------------------------------------------------------
DB_CONFIG = {
    "host": os.environ.get("DB_HOST", "localhost"),
    "port": int(os.environ.get("DB_PORT", "5432")),
    "dbname": os.environ.get("DB_NAME", "ecommerce"),
    "user": os.environ.get("DB_USER", "postgres"),
    "password": os.environ.get("DB_PASS", ""),
    "connect_timeout": int(os.environ.get("DB_CONNECT_TIMEOUT", "5")),
}
DB_POOL_MAX = int(os.environ.get("DB_POOL_MAX", "10"))

SCHEMA_LOCK_ID = 7002  # advisory lock so concurrent workers don't race on DDL
SCHEMA = """
CREATE TABLE IF NOT EXISTS products (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 101) PRIMARY KEY,
    name        TEXT          NOT NULL,
    price       NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    description TEXT          NOT NULL DEFAULT '',
    image_url   TEXT,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
"""
SEED_PRODUCTS = [
    ("Laptop", Decimal("1200.00"), "14-inch ultrabook with all-day battery life.", "/static/images/laptop.jpg"),
    ("Phone", Decimal("800.00"), "6.1-inch OLED display and a great camera.", "/static/images/phone.jpg"),
    ("Headphones", Decimal("150.00"), "Wireless noise-cancelling over-ear headphones.", "/static/images/headphones.jpg"),
    ("Smartwatch", Decimal("250.00"), "Fitness tracking, GPS and week-long battery.", "/static/images/smartwatch.jpg"),
]

_pool = None
_pool_lock = threading.Lock()


def initialise_schema(db_pool):
    """Create tables and seed demo data on first start."""
    conn = db_pool.getconn()
    try:
        with conn, conn.cursor() as cur:
            cur.execute("SELECT pg_advisory_xact_lock(%s)", (SCHEMA_LOCK_ID,))
            cur.execute(SCHEMA)
            cur.execute("SELECT COUNT(*) FROM products")
            if cur.fetchone()[0] == 0:
                cur.executemany(
                    "INSERT INTO products (name, price, description, image_url) VALUES (%s, %s, %s, %s)",
                    SEED_PRODUCTS,
                )
    finally:
        db_pool.putconn(conn)


def get_pool():
    """Lazily create the pool so the service can start before the DB is ready."""
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                new_pool = pool.ThreadedConnectionPool(1, DB_POOL_MAX, **DB_CONFIG)
                try:
                    initialise_schema(new_pool)
                except Exception:
                    new_pool.closeall()
                    raise
                _pool = new_pool
                logger.info("Connected to database %s@%s", DB_CONFIG["dbname"], DB_CONFIG["host"])
    return _pool


@contextmanager
def db_cursor():
    """Yield a dict cursor; commit on success, roll back on error."""
    db_pool = get_pool()
    conn = db_pool.getconn()
    try:
        with conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
            yield cur
    finally:
        db_pool.putconn(conn)


# --------------------------------------------------------------------------
# Validation helpers & error handling
# --------------------------------------------------------------------------
MAX_PRICE = Decimal("99999999.99")


class ValidationError(ValueError):
    """Raised when a request payload is invalid."""


def read_json_object():
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        raise ValidationError("Request body must be a JSON object")
    return data


def parse_price(value):
    if isinstance(value, bool) or not isinstance(value, (int, float, str)):
        raise ValidationError("'price' must be a number")
    try:
        price = Decimal(str(value).strip())
    except InvalidOperation:
        raise ValidationError("'price' must be a number") from None
    if not price.is_finite() or price < 0 or price > MAX_PRICE:
        raise ValidationError(f"'price' must be between 0 and {MAX_PRICE}")
    return price.quantize(Decimal("0.01"))


def parse_product(data):
    name = data.get("name")
    if not isinstance(name, str) or not 1 <= len(name.strip()) <= 120:
        raise ValidationError("'name' is required (1-120 characters)")

    description = data.get("description") or ""
    if not isinstance(description, str) or len(description) > 1000:
        raise ValidationError("'description' must be a string of at most 1000 characters")

    image_url = data.get("image_url") or None
    if image_url is not None:
        if not isinstance(image_url, str) or len(image_url) > 500:
            raise ValidationError("'image_url' must be a string of at most 500 characters")
        if not image_url.startswith(("http://", "https://", "/")):
            raise ValidationError("'image_url' must be an http(s) URL or an absolute path")

    return name.strip(), parse_price(data.get("price")), description.strip(), image_url


def serialize(row):
    product = dict(row)
    product["price"] = float(product["price"])
    product["created_at"] = product["created_at"].isoformat()
    return product


@app.errorhandler(ValidationError)
def handle_validation_error(err):
    return jsonify(error=str(err)), 400


@app.errorhandler(HTTPException)
def handle_http_error(err):
    return jsonify(error=err.description or err.name), err.code


@app.errorhandler(psycopg2.OperationalError)
@app.errorhandler(pool.PoolError)
def handle_db_unavailable(err):
    logger.error("Database unavailable: %s", err)
    return jsonify(error="Database unavailable"), 503


@app.errorhandler(Exception)
def handle_unexpected(err):
    logger.exception("Unhandled error")
    return jsonify(error="Internal server error"), 500


# --------------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------------
PRODUCT_COLUMNS = "id, name, price, description, image_url, created_at"


@app.get("/health")
def health():
    with db_cursor() as cur:
        cur.execute("SELECT 1")
    return jsonify(status="ok")


@app.get("/products")
def list_products():
    ids_param = request.args.get("ids")
    with db_cursor() as cur:
        if ids_param:
            try:
                ids = [int(i.strip()) for i in ids_param.split(",") if i.strip()]
            except ValueError:
                abort(400, description="Invalid 'ids' parameter; must be comma-separated integers")
            if not ids:
                return jsonify([])
            cur.execute(f"SELECT {PRODUCT_COLUMNS} FROM products WHERE id = ANY(%s) ORDER BY id", (ids,))
        else:
            cur.execute(f"SELECT {PRODUCT_COLUMNS} FROM products ORDER BY id")
        return jsonify([serialize(row) for row in cur.fetchall()])


@app.get("/products/<int:product_id>")
def get_product(product_id):
    with db_cursor() as cur:
        cur.execute(f"SELECT {PRODUCT_COLUMNS} FROM products WHERE id = %s", (product_id,))
        row = cur.fetchone()
    if row is None:
        abort(404, description="Product not found")
    return jsonify(serialize(row))


@app.post("/products")
def create_product():
    name, price, description, image_url = parse_product(read_json_object())
    with db_cursor() as cur:
        cur.execute(
            "INSERT INTO products (name, price, description, image_url) "
            f"VALUES (%s, %s, %s, %s) RETURNING {PRODUCT_COLUMNS}",
            (name, price, description, image_url),
        )
        product = serialize(cur.fetchone())
    return jsonify(product), 201, {"Location": url_for("get_product", product_id=product["id"])}


@app.delete("/products/<int:product_id>")
def delete_product(product_id):
    with db_cursor() as cur:
        cur.execute("DELETE FROM products WHERE id = %s RETURNING id", (product_id,))
        deleted = cur.fetchone()
    if deleted is None:
        abort(404, description="Product not found")
    return "", 204


if __name__ == "__main__":
    app.run(
        host=os.environ.get("HOST", "0.0.0.0"),
        port=int(os.environ.get("PORT", "5002")),
        debug=os.environ.get("FLASK_DEBUG") == "1",
    )
