"""Uploads service: validates and stores images locally or in S3.

Storage defaults to the local filesystem (UPLOAD_DIR). Set S3_BUCKET to store
objects in S3 instead; downloads then redirect to a short-lived presigned URL.
"""
import logging
import os
import re
import shutil
import uuid
from functools import lru_cache
from pathlib import Path

from flask import Flask, abort, jsonify, redirect, request, send_from_directory
from werkzeug.exceptions import HTTPException

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("uploads-api")

app = Flask(__name__)

UPLOAD_DIR = Path(os.environ.get("UPLOAD_DIR", Path(__file__).resolve().parent / "uploads"))
S3_BUCKET = os.environ.get("S3_BUCKET")
MAX_UPLOAD_MB = int(os.environ.get("MAX_UPLOAD_MB", "5"))
app.config["MAX_CONTENT_LENGTH"] = MAX_UPLOAD_MB * 1024 * 1024

# Stored names are generated by us, so this also guards the download route.
STORED_NAME_RE = re.compile(r"^[0-9a-f]{32}\.(png|jpg|gif|webp)$")


def detect_image_type(header):
    """Identify an image from its magic bytes; returns (extension, mime) or None."""
    if header.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png", "image/png"
    if header.startswith(b"\xff\xd8\xff"):
        return "jpg", "image/jpeg"
    if header[:6] in (b"GIF87a", b"GIF89a"):
        return "gif", "image/gif"
    if header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        return "webp", "image/webp"
    return None


@lru_cache(maxsize=1)
def s3_client():
    import boto3  # imported lazily so local-storage mode needs no AWS setup

    return boto3.client("s3", region_name=os.environ.get("AWS_REGION"))


def store_file(stream, name, content_type):
    if S3_BUCKET:
        s3_client().upload_fileobj(
            stream, S3_BUCKET, name, ExtraArgs={"ContentType": content_type}
        )
    else:
        UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
        with open(UPLOAD_DIR / name, "wb") as out:
            shutil.copyfileobj(stream, out)


@app.errorhandler(HTTPException)
def handle_http_error(err):
    return jsonify(error=err.description or err.name), err.code


@app.errorhandler(Exception)
def handle_unexpected(err):
    logger.exception("Unhandled error")
    return jsonify(error="Internal server error"), 500


@app.get("/health")
def health():
    return jsonify(status="ok", storage="s3" if S3_BUCKET else "local")


@app.post("/upload")
def upload_image():
    file = request.files.get("file") or request.files.get("image")
    if file is None or not file.filename:
        abort(400, description="No file provided (send multipart field 'file')")

    detected = detect_image_type(file.stream.read(16))
    file.stream.seek(0)
    if detected is None:
        abort(415, description="Unsupported file type; use PNG, JPEG, GIF or WebP")
    extension, content_type = detected

    file.stream.seek(0, os.SEEK_END)
    size = file.stream.tell()
    file.stream.seek(0)

    name = f"{uuid.uuid4().hex}.{extension}"
    store_file(file.stream, name, content_type)
    logger.info("Stored upload %s (%d bytes)", name, size)

    return (
        jsonify(
            message="Image uploaded",
            filename=name,
            url=f"/uploads/{name}",
            content_type=content_type,
            size=size,
        ),
        201,
    )


@app.get("/uploads/<filename>")
def get_upload(filename):
    if not STORED_NAME_RE.match(filename):
        abort(404, description="File not found")
    if S3_BUCKET:
        url = s3_client().generate_presigned_url(
            "get_object", Params={"Bucket": S3_BUCKET, "Key": filename}, ExpiresIn=300
        )
        return redirect(url)
    return send_from_directory(UPLOAD_DIR, filename, max_age=86400)


if __name__ == "__main__":
    app.run(
        host=os.environ.get("HOST", "0.0.0.0"),
        port=int(os.environ.get("PORT", "5004")),
        debug=os.environ.get("FLASK_DEBUG") == "1",
    )
